version: '3.8'

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db1
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql